public enum LevelName {
  EMERALD_FOREST, 
  EMERALD_FOREST_CAVE,
  KIT_PRISM_INNER, 
  WORLD_PRISM_INNER, 
  CASTLE_APPROACH, 
  CASTLE_COURTYARD,
  CASTLE_HUB, 
  LIBRARY, 
  THRONE_ROOM, 
  MASTER_BEDROOM, 
  KIT_BEDROOM,
  SPIRE, 
  TEST_0, 
  TEST_1;
}